### ISSUE TITLE
Implement `ReadDir()` for SFTP & SMB

### ISSUE THREAD

**Issue by adityathebe** [flanksource/artifacts#17]
It's used by canary-checker folder check.

**Comment by moshloop** [comment]
+ E2E tests using:

- https://hub.docker.com/r/instantlinux/samba  / https://github.com/instantlinux/docker-tools/tree/main/images/samba/helm
- https://github.com/fsouza/fake-gcs-server
- https://hub.docker.com/r/atmoz/sftp/
